# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Yarn install, lint, typecheck, test
      run: |
        yarn install
        yarn lint
        yarn typecheck
        yarn test
